# `yastyleguide` style file for nitpick
# for users use: https://raw.githubusercontent.com/levkovalenko/yastyleguide-styles/master/nitpick-yastyle.toml

[nitpick]
minimum_version = "0.22.0"

[nitpick.styles]
include = [
  "flake8.toml",
  "yastyleguide.toml",
  "isort.toml",
  "black.toml",
  "mypy.toml",
  "pre-commit.toml",
  "commitizen.toml",
]
