# `yastyleguide` style file for nitpick
# for users use: https://raw.githubusercontent.com/levkovalenko/yastyleguide/master/styles/nitpick-yastyle.toml

[nitpick]
minimum_version = "0.22.0"

[nitpick.styles]
include = [
    "flake8.toml",
    "yastyleguide.toml",
    "isort.toml",
]

[nitpick.files."setup.cfg"]
comma_separated_values = [
    "flake8.ignore",
    "flake8.exclude",
    "flake8.per-file-ignores",
]