# Nitpick settings for pre-commit

[nitpick.meta]
name = "pre-commit hooks for Python projects"
url = "https://pre-commit.com/hooks"

[".pre-commit-config.yaml"]
default_stages = ["commit", "push"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v4.4.0"

[[".pre-commit-config.yaml".repos.hooks]]
id = "trailing-whitespace"

[[".pre-commit-config.yaml".repos.hooks]]
id = "end-of-file-fixer"

[[".pre-commit-config.yaml".repos.hooks]]
id = "check-yaml"

[[".pre-commit-config.yaml".repos.hooks]]
id = "check-added-large-files"

[[".pre-commit-config.yaml".repos.hooks]]
id = "check-ast"

[[".pre-commit-config.yaml".repos.hooks]]
id = "check-merge-conflict"
stages = ["commit"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/python/black"
rev = "23.1.0"

[[".pre-commit-config.yaml".repos.hooks]]
id = "black"
stages = ["commit"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pycqa/isort"
rev = "5.12.0"

[[".pre-commit-config.yaml".repos.hooks]]
id = "isort"
name = "isort (python)"
stages = ["commit"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/flake8"
rev = "6.0.0"

[[".pre-commit-config.yaml".repos.hooks]]
additional_dependencies = ["yastyleguide==0.2.0"]
id = "flake8"
stages = ["commit"]


[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v2.42.1"

[[".pre-commit-config.yaml".repos.hooks]]
id = "commitizen"
stages = ["commit-msg"]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/andreoliwa/nitpick"
rev = "v0.32.0"

[[".pre-commit-config.yaml".repos.hooks]]
additional_dependencies = ["requests-cache==0.9.8"]
id = "nitpick"
