# Nitpick settings yastyleguide

["pyproject.toml".tool.flake8]
# Basic settings for flake8
count = true
show-source = true
statistics = true
# We ignore next errors:
# D100 - missing docstrings for modules
# D104 - missing docstrings for packages
# W503 - broken line befor binary operator
# ANN002 - missing type annotation for *args
# ANN003 - missing type annotation for **kwargs
# ANN101 - missing type annotation for self in method
# ANN102 - missing type annotation for cls in classmethod
# ANN102 - missing return annotation for magic methods
# S101 - assert for tests
# D103 - docstrings for tests
# F401 - import for init files
# We belive that we don't need this errors for our linter.
ignore = ["D100", "D104", "W503", "ANN002", "ANN003", "ANN101", "ANN102", "ANN204"]
per-file-ignores = [
  "tests/**.py:S101,D103",
  "**__init__.py:F401",
]

# Line settings
max-line-length = 88

# Quotes settings
inline-quotes = "\""

# Complexisty settings
max-annotations-complexity = 4
max-complexity = 3
max-expression-complexity = 9
max-line-complexity = 15

# Docstrings conv
docstring-convention = 'google'

# Spellchecker dictionaries
dictionaries = ["en_US", "python", "technical", "pandas"]
