# Nitpick settings yastyleguide

["setup.cfg".flake8]
# Basic settings for flake8
count = true
show-source = true
statistics = true
# We ignore next errors:
# D100 - missing docstrings for modules
# D104 - missing docstrings for packages
# W503 - broken line befor binary operator
# PD015 - no `pd.merge`, only df.merge
# S101 - assert for tests
# D103 - docstrings for tests
# F401 - import for init files
# We belive that we don't need this errors for our linter.
ignore = "D100,D104,W503,PD015"
per-file-ignores = "tests/**.py:S101,D103,**__init__.py:F401,"

# Line settings
max-line-length = 88

# Quotes settings
inline-quotes = '"'

# Complexisty settings
max-complexity = 5
max-expression-complexity = 9
max-annotations-complexity = 4
max-line-complexity = 15

# Docstrings conv
docstring-convention = 'google'

